// React/src/samples/tabstrip/scrolling/tabstrip-scroll-to.js
import React, { Component } from 'react';

import { IntegralUIAnimationType, IntegralUITabScrollMode, IntegralUITheme } from 'integralui-web/components/integralui.enums.js';

import IntegralUISelectComponent from 'integralui-web/wrappers/react.integralui.select.js';
import IntegralUITabComponent from 'integralui-web/wrappers/react.integralui.tab.js';
import IntegralUITabStripComponent from 'integralui-web/wrappers/react.integralui.tabstrip.js';

import './tabstrip-scroll-to.css';

class TabStripScrollTo extends Component {
    constructor(props){
        super(props);

        this.state = {
            currentAnimation: IntegralUIAnimationType.Fade,
            currentResourcePath: '../../integralui-web/icons',
            currentScrollMode: IntegralUITabScrollMode.InBound,
            currentSelection: null,
            currentTheme: IntegralUITheme.Office,
            isAnimationAllowed: true,
            ctrlSize: { width: 600, height: 300 },
            tabs: []
        }

        this.tabstripRef = React.createRef();
    }

    componentDidMount(){
        let tabList = [];
        for (let i = 1; i <= 15; i++)
            tabList.push({ id: i, text: 'Tab' + i });

        this.setState({ tabs: tabList });
    }

    scrollToChanged(e){
        let tab = this.state.tabs[e.detail.index];
        this.tabstripRef.current.scrollTo(tab);
        this.setState({ currentSelection: tab });
    }

    render() {
        var tabs = this.state.tabs.map((tab, index) => {
            return (
                <IntegralUITabComponent key={index} data={tab} text={tab.text} theme={this.state.currentTheme}>
                    <div className="tbs-scrollto-tab-content">Content of {tab.text}</div>
                </IntegralUITabComponent>
            )
        });

        return (
            <div>
                <h2>TabStrip / Scroll To Specific Tab</h2>
                <div className="sample-block">
                    <IntegralUITabStripComponent id="tabstrip-scrollto" ref={this.tabstripRef}
                        allowAnimation={this.state.isAnimationAllowed}
                        contentAnimation={this.state.currentAnimation}
                        resourcePath={this.state.currentResourcePath}
                        scrollMode={this.state.currentScrollMode}
                        selectedTab={this.state.currentSelection}
                        size={this.state.ctrlSize}
                        tabStripPlacement={this.state.currentPlacement} 
                        theme={this.state.currentTheme} 
                    > 
                        {tabs}
                    </IntegralUITabStripComponent>
                    <div className="tabstrip-scrollto-panel">
                        <label>Scroll to: </label>
                        <IntegralUISelectComponent allowAnimation={true} items={this.state.tabs} resourcePath={this.state.currentResourcePath} theme={this.state.currentTheme} selectedIndexChanged={(e) => this.scrollToChanged(e)}></IntegralUISelectComponent>
                    </div>
                    <div className="feature-help">
                        <p><span className="initial-space"></span>In this example, there are multiple tabs and you can select the tab that you want to appear in view by scrolling to it.</p>
                    </div>
                </div>
            </div>
        );
    }
}

export default TabStripScrollTo;

// Angular/src/app/samples/tabstrip/scrolling/tabstrip-scroll-to.ts
import { Component, ElementRef, ViewChild } from '@angular/core';

import 'integralui-web/components/integralui.select';
import 'integralui-web/components/integralui.tab';
import 'integralui-web/components/integralui.tabstrip';
import { IntegralUIAnimationType, IntegralUITabScrollMode, IntegralUITheme } from 'integralui-web/components/integralui.enums';

@Component({
    selector: '',
    templateUrl: './tabstrip-scroll-to.html',
    styleUrls: ['./tabstrip-scroll-to.css']
})
export class TabStripScrollTo {
    @ViewChild('tabstrip', { static: false }) tabstrip!: ElementRef;

    public currentAnimation: IntegralUIAnimationType = IntegralUIAnimationType.Slide;
    public currentResourcePath: string = 'assets/icons';
    public currentScrollMode: IntegralUITabScrollMode = IntegralUITabScrollMode.InBound;
    public currentTheme: IntegralUITheme = IntegralUITheme.Office;
    public ctrlSize: any = { width: 600, height: 300 };
    public tabs: Array<any> = [];

    constructor(){
        for (let i = 1; i <= 15; i++)
            this.tabs.push({ id: i, text: 'Tab' + i });
    }

    scrollToChanged(e: any){
        let tab = this.tabs[e.detail.index];
        this.tabstrip.nativeElement.scrollTo(tab);
        this.tabstrip.nativeElement.selectedTab = tab;
    }
}
