// React/src/samples/listbox/dragdrop/listbox-dragdrop-overview.js
import React, { Component } from 'react';
import { html } from 'integralui-web/external/lit-element.js';

import IntegralUIListBoxComponent from 'integralui-web/wrappers/react.integralui.listbox.js';
import IntegralUIRadioButtonComponent from 'integralui-web/wrappers/react.integralui.radiobutton.js';
import IntegralUIRadioGroupComponent from 'integralui-web/wrappers/react.integralui.radiogroup.js';
import { IntegralUIDragDropMode, IntegralUISelectionMode, IntegralUITheme } from 'integralui-web/components/integralui.enums.js';

import './listbox-dragdrop-overview.css';
import { iuiListBoxDragDropOverviewStyle } from './listbox-dragdrop-overview.style.js';

class ListBoxDDOverview extends Component {

    //
    // Initialization / Destruction --------------------------------------------------------------
    //

    constructor(props){
        super(props);

        this.state = {
            ctrlSize: { width: 350, height: 400 },
            currentDragDropMode: IntegralUIDragDropMode.Dynamic,
            currentResourcePath: '../../integralui-web/icons',
            currentSelectionMode: IntegralUISelectionMode.MultiExtended,
            currentTheme: IntegralUITheme.Office,
            groups: [
                { name: "sci-fi" },
                { name: "adventure" },
                { name: "action" },
                { name: "drama" },
                { name: "music" },
                { name: "comedy" },
                { name: "biography" },
                { name: "crime" },
                { name: "western" },
                { name: "horror" },
                { name: "romance" }
            ],
            items: [
                { id: 1, icon: "sci-fi", text: "Star Trek", year: "2009", rating: 8.0 },
                { id: 2, icon: "adventure", text: "Cast Away", year: "2000", rating: 7.7  },
                { id: 3, icon: "action", text: "Gladiator", year: "2000", rating: 8.5 },
                { id: 4, icon: "drama", text: "Malèna", year: "2000", rating: 7.5 },
                { id: 5, icon: "music", text: "Moulin Rouge", year: "2001", rating: 7.6 },
                { id: 6, icon: "comedy", text: "Snatch", year: "2000", rating: 8.3  },
                { id: 7, icon: "biography", text: "A Beautiful Mind", year: "2001", rating: 8.2  },
                { id: 8, icon: "crime", text: "Black Hawk Down", year: "2001", rating: 7.7 },
                { id: 9, icon: "western", text: "Django Unchained", year: "2012", rating: 8.5  },
                { id: 10, icon: "sci-fi", text: "Man of Steel", year: "2013", rating: 7.2 },
                { id: 11, icon: "horror", text: "The Ring", year: "2002", rating: 7.1 },
                { id: 12, icon: "romance", text: "40 Days and 40 Nights", year: "2002", rating: 5.6 },
                { id: 13, icon: "sci-fi", text: "Minority Report", year: "2002", rating: 7.7 },
                { id: 14, icon: "comedy", text: "Scary Movie 3", year: "2003", rating: 5.5 },
                { id: 15, icon: "music", text: "Walk the Line", year: "2005", rating: 7.9  },
                { id: 16, icon: "romance", text: "How to Lose a Guy in 10 Days", year: "2003", rating: 6.4 },
                { id: 17, icon: "crime", text: "The Dark Knight", year: "2008", rating: 9.0  },
                { id: 18, icon: "horror", text: "American Psycho", year: "2000", rating: 7.6 },
                { id: 19, icon: "drama", text: "The Grand Budapest Hotel", year: "2014", rating: 8.1 },
                { id: 20, icon: "comedy", text: "The Wolf of Wall Street", year: "2013", rating: 8.2 }
            ],

            // Control PaneL
            allowDrag: true,
            allowDrop: true,
            isGrouped: true
        }

        this.listRef = React.createRef();
    }

    componentDidMount(){
        // Apply grouping
        this.state.items.forEach(item => item.group = item.icon);
        this.listRef.current.updateLayout();
    }

    // Templates ---------------------------------------------------------------------------------

    currentItemTemplate = (item) => { 
        if (item.type === 'group')
            return html`
                    <div class="lbox-ddovw-item-content-group">
                        <span class="lbox-ddovw-icons ${item.name}"></span>
                        <span class="lbox-ddovw-name">${item.name}</span>
                    </div>
                `;
        else
            return html`
                <div class="lbox-ddovw-item-content">
                    <span class="lbox-ddovw-title">${item.text}</span>
                    <span class="lbox-ddovw-year">${item.year}</span>
                </div>
            `;
    }

    // Events ------------------------------------------------------------------------------------

    onDragDropModeChecked(e){
        switch (e.detail.index){
            case 0: 
                this.setState({ currentDragDropMode: IntegralUIDragDropMode.Static });
                break;

            default: 
                this.setState({ currentDragDropMode: IntegralUIDragDropMode.Dynamic });
                break;
        }
    }

    // Update ------------------------------------------------------------------------------------

    render() {
        return (
            <div>
                <h2>ListBox / Drag Drop Overview</h2>
                <div className="sample-block">
                    <IntegralUIListBoxComponent id="listbox-dragdrop-overview" ref={this.listRef}
                        allowDrag={this.state.allowDrag}
                        allowDrop={this.state.allowDrop}
                        customStyle={iuiListBoxDragDropOverviewStyle}
                        dragDropMode={this.state.currentDragDropMode}
                        groups={this.state.groups}
                        items={this.state.items}
                        itemTemplate={this.currentItemTemplate}
                        resourcePath={this.state.currentResourcePath}
                        selectionMode={this.state.currentSelectionMode}
                        showGroups={this.state.isGrouped}
                        size={this.state.ctrlSize}
                        theme={this.state.currentTheme} 
                    ></IntegralUIListBoxComponent>
                    <div className="sample-block-ddlb-control-panel">
                        <label><input type="checkbox" defaultChecked={this.state.allowDrag} onChange={(e) => this.setState({ allowDrag: e.target.checked})} /> Allow Drag</label>
                        <label><input type="checkbox" defaultChecked={this.state.allowDrop} onChange={(e) => this.setState({ allowDrop: e.target.checked})} /> Allow Drop</label>
                        <label><input type="checkbox" defaultChecked={this.state.isGrouped} onChange={(e) => this.setState({ isGrouped: e.target.checked})} /> Show Groups</label>
                        <br/>
                        <label>Drag Drop Mode: </label>
                        <IntegralUIRadioGroupComponent theme={this.state.currentTheme} buttonChecked={(e) => this.onDragDropModeChecked(e)}>
                            <IntegralUIRadioButtonComponent>Static</IntegralUIRadioButtonComponent>
                            <IntegralUIRadioButtonComponent checked={true}>Dynamic</IntegralUIRadioButtonComponent>
                        </IntegralUIRadioGroupComponent>
                    </div>
                </div>
                <div className="feature-help" style={{ marginTop: '20px' }}>
                    <p><span className="initial-space"></span>In this sample you can drag drop items within the same ListBox. There are two different ways to drag and drop items:</p>
                    <ul className="feature-points">
                        <li><span className="code-name">Static</span> - a drop marker appears with information about target item and an icon that shows drop position: Up or Down</li>
                        <li><span className="code-name">Dynamic</span> - a window with a list of dragged items appears and while dragging it all other items will move making space where items can drop</li>
                    </ul>
                    <p><span className="initial-space"></span>During drag drop operations, you can also create a copy of an item by holding the SHIFT key. In Static mode the dragging window will change its icon, showing a <span style={{ color: '#c60d0d', fontWeight: 'bold' }}>+</span> sign next to the position marker, while in Dynamic mode a <span style={{ color: '#c60d0d', fontWeight: 'bold' }}>copy/paste</span> icon will appear in the center of the dragging window.</p>
                    <br/>
                    <p><span className="initial-space"></span>By clicking on check boxes, you can change the built-in properties:</p>
                    <ul className="feature-points">
                        <li><span className="code-name">allowDrag</span> - determines whether items can be dragged</li>
                        <li><span className="code-name">allowDrop</span> - determines whether items can be dropped</li>
                        <li><span className="code-name">showGroups</span> - determines whether items are displayed n groups</li>
                        <li><span className="code-name">dragDropMode</span> - determines whether drag and drop is Static or Dynamic</li>
                    </ul>
                </div>
            </div>
        );
    }
}

export default ListBoxDDOverview;

// Angular/src/app/samples/listbox/dragdrop/listbox-dragdrop-overview.ts
import { Component, ElementRef, ViewChild } from '@angular/core';
import { html } from 'integralui-web/external/lit-element';

import 'integralui-web/components/integralui.listbox';
import 'integralui-web/components/integralui.radiobutton';
import 'integralui-web/components/integralui.radiogroup';
import { IntegralUIDragDropMode, IntegralUISelectionMode, IntegralUITheme } from 'integralui-web/components/integralui.enums';
import { iuiListBoxDragDropOverviewStyle } from './listbox-dragdrop-overview.style';

@Component({
    selector: '',
    templateUrl: './listbox-dragdrop-overview.html',
    styleUrls: ['./listbox-dragdrop-overview.css']
})
export class ListBoxDDOverview {
    @ViewChild('listbox', { static: false }) listbox!: ElementRef;

    public ctrlSize: any = { width: 350, height: 400 }
    public currentDragDropMode: IntegralUIDragDropMode = IntegralUIDragDropMode.Dynamic;
    public currentResourcePath: string = 'assets/icons';
    public currentSelectionMode: IntegralUISelectionMode = IntegralUISelectionMode.MultiExtended;
    public currentTheme: IntegralUITheme = IntegralUITheme.Office;
    public groups: Array<any> = [];
    public items: Array<any> = [];
    public listStyle: any = iuiListBoxDragDropOverviewStyle;

    // Control PaneL
    public allowDrag: boolean = true;
    public allowDrop: boolean = true;
    public isGrouped: boolean = true;

    // Initialization ----------------------------------------------------------------------------

    constructor(){
        this.groups = [
            { name: "sci-fi" },
            { name: "adventure" },
            { name: "action" },
            { name: "drama" },
            { name: "music" },
            { name: "comedy" },
            { name: "biography" },
            { name: "crime" },
            { name: "western" },
            { name: "horror" },
            { name: "romance" }
        ];

        this.items = [
            { id: 1, icon: "sci-fi", text: "Star Trek", year: "2009", rating: 8.0 },
            { id: 2, icon: "adventure", text: "Cast Away", year: "2000", rating: 7.7  },
            { id: 3, icon: "action", text: "Gladiator", year: "2000", rating: 8.5 },
            { id: 4, icon: "drama", text: "Malèna", year: "2000", rating: 7.5 },
            { id: 5, icon: "music", text: "Moulin Rouge", year: "2001", rating: 7.6 },
            { id: 6, icon: "comedy", text: "Snatch", year: "2000", rating: 8.3  },
            { id: 7, icon: "biography", text: "A Beautiful Mind", year: "2001", rating: 8.2  },
            { id: 8, icon: "crime", text: "Black Hawk Down", year: "2001", rating: 7.7 },
            { id: 9, icon: "western", text: "Django Unchained", year: "2012", rating: 8.5  },
            { id: 10, icon: "sci-fi", text: "Man of Steel", year: "2013", rating: 7.2 },
            { id: 11, icon: "horror", text: "The Ring", year: "2002", rating: 7.1 },
            { id: 12, icon: "romance", text: "40 Days and 40 Nights", year: "2002", rating: 5.6 },
            { id: 13, icon: "sci-fi", text: "Minority Report", year: "2002", rating: 7.7 },
            { id: 14, icon: "comedy", text: "Scary Movie 3", year: "2003", rating: 5.5 },
            { id: 15, icon: "music", text: "Walk the Line", year: "2005", rating: 7.9  },
            { id: 16, icon: "romance", text: "How to Lose a Guy in 10 Days", year: "2003", rating: 6.4 },
            { id: 17, icon: "crime", text: "The Dark Knight", year: "2008", rating: 9.0  },
            { id: 18, icon: "horror", text: "American Psycho", year: "2000", rating: 7.6 },
            { id: 19, icon: "drama", text: "The Grand Budapest Hotel", year: "2014", rating: 8.1 },
            { id: 20, icon: "comedy", text: "The Wolf of Wall Street", year: "2013", rating: 8.2 }
        ];
    }   

    ngAfterViewInit(){
        // Apply grouping
        this.items.forEach(item => item.group = item.icon);
        this.listbox.nativeElement.updateLayout();
    }

    // Templates ---------------------------------------------------------------------------------

    currentItemTemplate = (item: any) => { 
        if (item.type === 'group')
            return html`
                    <div class="lbox-ddovw-item-content-group">
                        <span class="lbox-ddovw-icons ${item.name}"></span>
                        <span class="lbox-ddovw-name">${item.name}</span>
                    </div>
                `;
        else
            return html`
                <div class="lbox-ddovw-item-content">
                    <span class="lbox-ddovw-title">${item.text}</span>
                    <span class="lbox-ddovw-year">${item.year}</span>
                </div>
            `;
    }

    // Events ------------------------------------------------------------------------------------

    onDragDropModeChecked(e: any){
        switch (e.detail.index){
            case 0: 
                this.currentDragDropMode = IntegralUIDragDropMode.Static;
                break;

            default: 
                this.currentDragDropMode = IntegralUIDragDropMode.Dynamic;
                break;
        }
    }
}
