// React/src/samples/contextmenu/contextmenu-checkbox.js
import React, { Component } from 'react';

import IntegralUIContextMenuComponent from 'integralui-web/wrappers/react.integralui.contextmenu.js';
import { IntegralUITheme } from 'integralui-web/components/integralui.enums.js';

import './contextmenu-checkbox.css';
import { iuiContextMenuCheckBoxStyle } from './contextmenu-checkbox.style.js';

class ContextMenuCheckBoxes extends Component {

    //
    // Initialization / Destruction --------------------------------------------------------------
    //

    constructor(props){
        super(props);

        this.state = {
            currentResourcePath: '../integralui-web/icons',
            currentTheme: IntegralUITheme.Office,
            menuSettings: {
                items: [
                    { id: 31, text: "Auto Preview", icon: "icons-medium empty" },
                    { id: 32, type: "separator" },
                    {
                        id: 33, 
                        text: "Toolbars", 
                        icon: "icons-medium empty",
                        items: [
                            { id: 331, pid: 33, text: "Standard", allowCheckBox: true, checked: true },
                            { id: 332, pid: 33, text: "Advanced", allowCheckBox: true },
                            { id: 333, pid: 33, text: "Web", allowCheckBox: true },
                            { id: 334, pid: 33, type: "separator" },
                            { id: 335, pid: 33, text: "Customize ...", icon: "icons-medium empty" }
                        ]
                    },
                    { id: 34, text: "StatusBar", allowCheckBox: true },
                    { id: 35, type: "separator" },
                    { id: 36, text: "Refresh", icon: "icons-medium empty" }
                ]
            }
        }
    }

    // Events ------------------------------------------------------------------------------------

    onMenuChecked(e){
        console.log(e.detail.item.text + " is now " + e.detail.checked);
    }

    // Update ------------------------------------------------------------------------------------

    render() {
        return (
            <div>
                <h2>ContextMenu / Check Boxes</h2>
                <div className="sample-block">
                    <IntegralUIContextMenuComponent
                        customStyle={iuiContextMenuCheckBoxStyle}
                        resourcePath={this.state.currentResourcePath}
                        settings={this.state.menuSettings}
                        theme={this.state.currentTheme}
                        checkedChanged={(e) => this.onMenuChecked(e)}
                    > 
                        <div className="cmnu-checkbox-block" id="menu-block">
                            <span>Right click to open the context menu</span>
                        </div>
                    </IntegralUIContextMenuComponent>
                    <div className="feature-help">
                        <p><span className="initial-space"></span>An example of a Context Menu with Check Boxes. Opening the <strong>'Toolbars'</strong> menu will show three menu items with check boxes.</p>
                        <p><span className="initial-space"></span>Each item can have a checkbox, by setting the followiing fields:</p>
                        <ul className="feature-points">
                            <li><span className="code-name">allowCheckBox</span> - Determines whether checkbox is visible or not</li>
                            <li><span className="code-name">checked</span> - specifies whether the checkbox is checked or not</li>
                        </ul>
                        <p><span className="initial-space"></span>Whenever menu checkbox is clicked, the <span className="code-name">checkedChanged</span> event is fired, which you can handle in your code and add specific action.</p>
                        <p><span className="initial-space"></span>Clicking on the checkbox will not close the parent menu. This allows you to check multiples menu items without closing. To close the menu, click on the menu label or anywhere outside of the menu space.</p>
                        <p><span className="initial-space"></span>Check boxes are fully customizable via CSS.</p>
                    </div>
                </div>
            </div>
        );
    }
}

export default ContextMenuCheckBoxes;

// Angular/src/app/samples/contextmenu/contextmenu-checkbox.ts
/*
  Copyright © 2016-2023 Lidor Systems. All rights reserved.

  This file is part of the "IntegralUI Web" Library. 
                                                                   
  The contents of this file are subject to the IntegralUI Web License, and may not be used except in compliance with the License.
  A copy of the License should have been installed in the product's root installation directory or it can be found at
  http://www.lidorsystems.com/products/web/studio/license-agreement.aspx.
                                                            
  This SOFTWARE is provided "AS IS", WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the specific language 
  governing rights and limitations under the License. Any infringement will be prosecuted under applicable laws.                           
*/

import { Component, ElementRef, ViewChild } from '@angular/core';

import 'integralui-web/components/integralui.contextmenu';
import { IntegralUITheme } from 'integralui-web/components/integralui.enums';

import { iuiContextMenuCheckBoxStyle } from './contextmenu-checkbox.style';

@Component({
    selector: '',
    templateUrl: './contextmenu-checkbox.html',
    styleUrls: ['./contextmenu-checkbox.css']
})
export class ContextMenuCheckBoxes {
    public currentResourcePath: string = 'assets/icons';
    public currentTheme: IntegralUITheme = IntegralUITheme.Office;
    public customStyle: any = iuiContextMenuCheckBoxStyle;

    public menuSettings: any = {
        items: [
            { id: 31, text: "Auto Preview", icon: "icons-medium empty" },
            { id: 32, type: "separator" },
            {
                id: 33, 
                text: "Toolbars", 
                icon: "icons-medium empty",
                items: [
                    { id: 331, pid: 33, text: "Standard", allowCheckBox: true, checked: true },
                    { id: 332, pid: 33, text: "Advanced", allowCheckBox: true },
                    { id: 333, pid: 33, text: "Web", allowCheckBox: true },
                    { id: 334, pid: 33, type: "separator" },
                    { id: 335, pid: 33, text: "Customize ...", icon: "icons-medium empty" }
                ]
            },
            { id: 34, text: "StatusBar", allowCheckBox: true },
            { id: 35, type: "separator" },
            { id: 36, text: "Refresh", icon: "icons-medium empty" }
        ]
    }
    
    // Events ------------------------------------------------------------------------------------

    onMenuChecked(e: any){
        console.log(e.detail.item.text + " is now " + e.detail.checked);
    }
}
