// Angular/src/app/samples/treeview/data/treeview-load-json.ts
import { Component, ElementRef, ViewChild } from '@angular/core';
import { HttpClient } from '@angular/common/http';

import 'integralui-web/components/integralui.treeview';
import { IntegralUITheme } from 'integralui-web/components/integralui.enums';
import { iuiTreeViewLoadJSONStyle } from './treeview-load-json.style';

@Component({
    selector: '',
    templateUrl: './treeview-load-json.html',
    styleUrls: ['./treeview-load-json.css']
})
export class TreeViewLoadJSON {
    @ViewChild('treeview', { static: false }) treeview!: ElementRef;

    public ctrlSize: any = { width: 400, height: 400 };
    public currentResourcePath: string = 'assets/icons';
    public currentTheme: IntegralUITheme = IntegralUITheme.Office;
    public customStyle: any = iuiTreeViewLoadJSONStyle;
    public data: Array<any> = [];

    public treeFields: any = {
        id: 'itemId',
        expanded: 'isExpanded',
        pid: 'parentId',
        items: 'children',
        text: 'label'
    }

    constructor(private http: HttpClient){
    }   

    ngAfterViewInit(){
        // Load data into the TreeView from a JSON file
        this.loadFromJSON();
    }

    private loadFromJSON(){
        let self = this;

        // Use HTTP service to get data from the specified JSON file
        self.http.get("./assets/treeview-load-json-tree-data.json").subscribe((data: any) => {
            // Suspend the tree layout from updates, to increase performance
            self.treeview.nativeElement.suspendLayout();

            // Load data into the tree view
            self.treeview.nativeElement.loadData(data, null, self.treeFields, false);

            // Resume and update the tree layout
            self.treeview.nativeElement.resumeLayout();
        });
    }
}

// React/src/samples/treeview/data/treeview-load-json.js
import React, { Component } from 'react';

import IntegralUITreeViewComponent from 'integralui-web/wrappers/react.integralui.treeview.js';
import { IntegralUITheme } from 'integralui-web/components/integralui.enums.js';

import './treeview-load-json.css';
import { iuiTreeViewLoadJSONStyle } from './treeview-load-json.style.js';
import treeData from './treeview-load-json-tree-data.json';

class TreeViewLoadJSON extends Component {

    //
    // Initialization / Destruction --------------------------------------------------------------
    //

    constructor(props){
        super(props);

        this.state = {
            ctrlSize: { width: 400, height: 400 },
            currentResourcePath: '../../integralui-web/icons',
            currentTheme: IntegralUITheme.Office,
            data: [],
            treeFields: {
                id: 'itemId',
                expanded: 'isExpanded',
                pid: 'parentId',
                items: 'children',
                text: 'label'
            }
        }

        this.treeRef = React.createRef();
    }

    componentDidMount(){
        this.loadFromJSON();
    }

    loadFromJSON(){
        // Suspend the tree layout from updates, to increase performance
        this.treeRef.current.suspendLayout();

        // Load data into the tree view
        this.treeRef.current.loadData(treeData, null, this.state.treeFields, false);

        // Resume and update the tree layout
        this.treeRef.current.resumeLayout();
    }

    //
    // Methods -----------------------------------------------------------------------------------
    //

    // Update ------------------------------------------------------------------------------------

    render() {
        return (
            <div>
                <h2>TreeView / Load Data from JSON</h2>
                <div className="sample-block">
                    <IntegralUITreeViewComponent id="treeview-load-json" ref={this.treeRef}
                        customStyle={iuiTreeViewLoadJSONStyle}
                        dataFields={this.state.treeFields}
                        items={this.state.data}
                        resourcePath={this.state.currentResourcePath}
                        size={this.state.ctrlSize}
                        theme={this.state.currentTheme} 
                        > 
                    </IntegralUITreeViewComponent>
                </div>
                <div className="feature-help">
                    <p><span className="initial-space"></span>This sample shows how to populate the TreeView using JSON file as a data source. The data source has custom data fields, which are mapped to the ones used by the tree view.</p>
                    <p><span className="initial-space"></span>For data binding, use the <strong>dataFields</strong> property of the TreeView component. This property accepts an object that replaces the default field names with your own.</p>
                    <p><span className="initial-space"></span>You can find the JSON data file under /assets subfolder in this project.</p>
                </div>
            </div>
        );
    }
}

export default TreeViewLoadJSON;
