// React/src/samples/tabstrip/utility/tabstrip-close-button.js
import React, { Component } from 'react';
import { html } from 'integralui-web/external/lit-element.js';

import { IntegralUIAnimationType, IntegralUIObjectState } from 'integralui-web/components/integralui.enums.js';

import IntegralUITabComponent from 'integralui-web/wrappers/react.integralui.tab.js';
import IntegralUITabStripComponent from 'integralui-web/wrappers/react.integralui.tabstrip.js';

import './tabstrip-close-button.css';
import { iuiTabStripCloseButtonStyle } from './tabstrip-close-button.style.js';

class TabStripCloseButton extends Component {
    constructor(props){
        super(props);

        this.state = {
            currentAnimation: IntegralUIAnimationType.Fade,
            currentResourcePath: '../../integralui-web/icons',
            currentSelection: null,
            currentTabSpacing: 3,
            isAnimationAllowed: true,
            ctrlSize: { width: 600, height: 300 },
            tabs: [
                { 
                    id: 1,
                    icon: 'library',
                    text: 'Books',
                    body: 'Curabitur pretium tincidunt lacus. Nulla gravida orci a odio. Nullam varius, turpis et commodo pharetra, est eros bibendum elit, nec luctus magna felis sollicitudin mauris. Integer in mauris eu nibh euismod gravida. Duis ac tellus et risus vulputate vehicula. Donec lobortis risus a elit. Etiam tempor.'
                },
                { 
                    id: 2,
                    icon: 'album',
                    text: 'Music',
                    body: 'Pellentesque malesuada nulla a mi. Duis sapien sem, aliquet nec, commodo eget, consequat quis, neque. Aliquam faucibus, elit ut dictum aliquet, felis nisl adipiscing sapien, sed malesuada diam lacus eget erat. Cras mollis scelerisque nunc. Nullam arcu. Aliquam consequat.'
                },
                { 
                    id: 3,
                    icon: 'star-empty',
                    text: 'Favorites',
                    body: 'Fusce convallis, mauris imperdiet gravida bibendum, nisl turpis suscipit mauris, sed placerat ipsum urna sed risus. In convallis tellus a mauris. Curabitur non elit ut libero tristique sodales. Mauris a lacus. Donec mattis semper leo. In hac habitasse platea dictumst.'
                }
            ]
        }
    }

    //
    // Currently when using templates, the LitElement binding syntax is required
    // for properties, methods and events
    //
    currentTabTemplate = (tab) => { 
        let btnIcon = '../../integralui-web/icons/close.ico';

        return html`
            <div>
                <span class="tbs-cbtn-icons ${tab.icon}"></span>
                <span>${tab.text}</span>
                <img class="tab-close-button" src=${btnIcon} @mousedown="${(e) => this.closeButtonClicked(e, tab)}" />
            </div>
        `;
    };

    closeButtonClicked(e, tab){
        // Delete tabs only when left mouse button is clicked
        if (e.which === 1){
            let tabIndex = this.state.tabs.indexOf(tab);
            let newTabList = [...this.state.tabs];
            newTabList.splice(tabIndex, 1);

            // Set selection to a new tab 
            let newSelTab = this.state.currentSelection;
            if (tab.selected){
                let newSelIndex = tabIndex < newTabList.length ? tabIndex : newTabList.length - 1;
                newSelTab = newSelIndex >= 0 && newSelIndex < newTabList.length  ? newTabList[newSelIndex] : null;
            }

            this.setState({ tabs: newTabList, currentSelection: newSelTab });
        }

        e.stopPropagation();
    }

    render() {
        let emptyBlockStyle = { 
            border: 'thin solid #cecece', 
            fontSize: '2rem', 
            padding: '125px 20px',
            width: this.state.ctrlSize.width + 'px', 
            textAlign: 'center'
        }

        let tabs = this.state.tabs.map((tab, index) => {
                return (
                    <IntegralUITabComponent key={index} data={tab} icon={tab.icon} text={tab.text}>
                        <div className="tbs-cbtn-tab-content">{tab.body}</div>
                    </IntegralUITabComponent>
                )
            });

        return (
            <div>
                <h2>TabStrip / Tabs with Close Button</h2>
                <div className="sample-block">
                    { tabs.length > 0 && 
                        <IntegralUITabStripComponent id="tabstrip-close-button"
                            allowAnimation={this.state.isAnimationAllowed}
                            animation={this.state.currentAnimation}
                            customStyle={iuiTabStripCloseButtonStyle}
                            resourcePath={this.state.currentResourcePath}
                            selectedTab={this.state.currentSelection}
                            size={this.state.ctrlSize}
                            tabSpacing={this.state.currentTabSpacing}
                            tabTemplate={this.currentTabTemplate}
                        > 
                            {tabs}
                        </IntegralUITabStripComponent>
                    }
                    { tabs.length === 0 && <div style={emptyBlockStyle}>All Tabs are Deleted.</div>}
                    <div className="feature-help">
                        <p><span className="initial-space"></span>This sample shows tabs with close button in their header. You can delete tabs by clicking this button.</p>
                        <p><span className="initial-space"></span>Whenever you need to add custom content to the tab header, you can use custom template. This template can be shared between all tabs, or you can specify a different template for each tab separately.</p>
                        <p><span className="initial-space"></span>In this case, the template contains an icon, text and a close button, represented by an 'X' icon.</p>
                    </div>
                </div>
            </div>
        );
    }
}

export default TabStripCloseButton;

// Angular/src/app/samples/tabstrip/utility/tabstrip-close-button.ts
/*
  Copyright © 2016-2022 Lidor Systems. All rights reserved.

  This file is part of the "IntegralUI Web" Library. 
                                                                   
  The contents of this file are subject to the IntegralUI Web License, and may not be used except in compliance with the License.
  A copy of the License should have been installed in the product's root installation directory or it can be found at
  http://www.lidorsystems.com/products/web/studio/license-agreement.aspx.
                                                            
  This SOFTWARE is provided "AS IS", WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the specific language 
  governing rights and limitations under the License. Any infringement will be prosecuted under applicable laws.                           
*/

import { Component, ElementRef, ViewChild } from '@angular/core';
import { html } from 'integralui-web/external/lit-element';

import 'integralui-web/components/integralui.tab';
import 'integralui-web/components/integralui.tabstrip';
import { IntegralUIAnimationType, IntegralUIObjectState } from 'integralui-web/components/integralui.enums';
import { iuiTabStripCloseButtonStyle } from './tabstrip-close-button.style';

@Component({
    selector: '',
    templateUrl: './tabstrip-close-button.html',
    styleUrls: ['./tabstrip-close-button.css']
})
export class TabStripCloseButton {
    @ViewChild('tabstrip', { static: false }) tabstrip!: ElementRef;

    public currentAnimation: IntegralUIAnimationType = IntegralUIAnimationType.Fade;
    public currentResourcePath: string = 'assets/icons';
    public currentSelection: any = null;
    public currentTabSpacing: number = 3;
    public customStyle: any = iuiTabStripCloseButtonStyle;
    public ctrlSize: any = { width: 600, height: 300 };
    public tabs: Array<any> = [];

    constructor(){
        this.tabs = [
            { 
                id: 1,
                icon: 'library',
                text: 'Books',
                body: 'Curabitur pretium tincidunt lacus. Nulla gravida orci a odio. Nullam varius, turpis et commodo pharetra, est eros bibendum elit, nec luctus magna felis sollicitudin mauris. Integer in mauris eu nibh euismod gravida. Duis ac tellus et risus vulputate vehicula. Donec lobortis risus a elit. Etiam tempor.'
            },
            { 
                id: 2,
                icon: 'album',
                text: 'Music',
                body: 'Pellentesque malesuada nulla a mi. Duis sapien sem, aliquet nec, commodo eget, consequat quis, neque. Aliquam faucibus, elit ut dictum aliquet, felis nisl adipiscing sapien, sed malesuada diam lacus eget erat. Cras mollis scelerisque nunc. Nullam arcu. Aliquam consequat.'
            },
            { 
                id: 3,
                icon: 'star-empty',
                text: 'Favorites',
                body: 'Fusce convallis, mauris imperdiet gravida bibendum, nisl turpis suscipit mauris, sed placerat ipsum urna sed risus. In convallis tellus a mauris. Curabitur non elit ut libero tristique sodales. Mauris a lacus. Donec mattis semper leo. In hac habitasse platea dictumst.'
            }
        ];
    }

    ngAfterViewInit(){
        this.tabstrip.nativeElement.tabTemplate = this.currentTabTemplate;
    }

    //
    // Currently when using templates, the LitElement binding syntax is required
    // for properties, methods and events
    //
    currentTabTemplate = (tab: any) => { 
        let btnIcon = 'assets/icons/close.ico';

        return html`
            <div>
                <span class="tbs-cbtn-icons ${tab.icon}"></span>
                <span>${tab.text}</span>
                <img class="tab-close-button" src=${btnIcon} @mousedown="${(e: any) => this.closeButtonClicked(e, tab)}" />
            </div>
        `;
    };

    closeButtonClicked(e: any, tab: any){
        // Delete tabs only when left mouse button is clicked
        if (e.which === 1){
            let tabIndex = this.tabs.indexOf(tab);
            this.tabs.splice(tabIndex, 1);

            // Set selection to a new tab 
            let newSelTab = this.currentSelection;
            if (tab.selected){
                let newSelIndex = tabIndex < this.tabs.length ? tabIndex : this.tabs.length - 1;
                newSelTab = newSelIndex >= 0 && newSelIndex < this.tabs.length  ? this.tabs[newSelIndex] : null;
            }

            this.currentSelection = newSelTab;
        }

        e.stopPropagation();
    }
}
